// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dcuszfgxxepsvdyesgwq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRjdXN6Zmd4eGVwc3ZkeWVzZ3dxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY1NzIyNDMsImV4cCI6MjA1MjE0ODI0M30.itlL2usfCdDVdn2r4rROwoe-APy0il1xombHXv2Ut-U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);